name: build docker image and push dockerhub

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码到本地
        uses: actions/checkout@v2
      # 使用 QEMU 模拟器 Buildx 构建跨平台的镜像
      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v1

      - name: 安装 Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ndoras/alpine-node
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: 登录 dockerhub
        uses: docker/login-action@v1
        with:
          username: ndoras
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true